export const ErrorCodes = {
  // Auth
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_INVALID: 'OTP_INVALID',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',

  // Resources
  NOT_FOUND: 'NOT_FOUND',
  RESUME_NOT_FOUND: 'RESUME_NOT_FOUND',
  INTERVIEW_NOT_FOUND: 'INTERVIEW_NOT_FOUND',

  // Business
  INSUFFICIENT_CREDITS: 'INSUFFICIENT_CREDITS',
  INTERVIEW_ALREADY_ACTIVE: 'INTERVIEW_ALREADY_ACTIVE',
  INTERVIEW_COMPLETED: 'INTERVIEW_COMPLETED',

  // AI
  AI_PROVIDER_ERROR: 'AI_PROVIDER_ERROR',
  AI_RESPONSE_INVALID: 'AI_RESPONSE_INVALID',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // Server
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  QUEUE_ERROR: 'QUEUE_ERROR',
} as const

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes]
